"""Generate README results from the full comparison and a separate measurement."""
import argparse
import json
from pathlib import Path
import os
import subprocess
import sys
import time


def render(summary, benchmark):
    total = summary["total"]
    if benchmark["total"] != total or benchmark["accepted"] != summary["parser_accepted"]:
        raise ValueError("Benchmark counts differ from the comparison")
    def row(label, count):
        return f"| {label} | {count:,} | {100 * count / total:.2f}% |"
    return "\n".join([
        "<!-- Generated by scripts/readme.py. Do not edit. -->",
        "# aihc-cabal-syntax", "",
        "A small Haskell library that parses `.cabal` files for the aihc compiler.",
        "It provides package data, version ranges, and condition evaluation without a runtime dependency on Cabal or Cabal-syntax.",
        "It uses Megaparsec. It does not solve dependencies or build packages.", "",
        "## Hackage results", "",
        f"The fixed Hackage index contains **{total:,} file revisions**.",
        f"The reference parser is **Cabal-syntax {summary['reference_version']}**.", "",
        "| Result | Files | All files |", "| --- | ---: | ---: |",
        row("aihc-cabal-syntax accepts", summary["parser_accepted"]),
        row("Cabal-syntax accepts", summary["reference_accepted"]),
        row("Equal converted data", summary["outcomes"]["match"]), "",
        "An accepted file does not prove full compliance.",
        "The equality test compares complete `GenericPackageDescription` values after conversion of our AST.",
        "Conversion limits can also cause differences. This library is not a complete replacement for Cabal-syntax.", "",
        "## Parse benchmark", "",
        f"One process reads all **{total:,} revisions**, parses each file, and forces each result.", "",
        "| Measurement | Result |", "| --- | ---: |",
        f"| Elapsed time | {benchmark['elapsed_seconds']:.2f} s |",
        f"| Peak process memory (RSS) | {benchmark['peak_rss_bytes'] / 1048576:.2f} MiB |", "",
        f"Measured on `{benchmark['system']}` with GHC {benchmark['ghc_version']}, `-O2`, and one RTS capability.",
        "Time includes archive input, parsing, and result evaluation through `show`.",
        "The benchmark includes rejected files. It discards each result before the next file.",
        "This is one measurement, not a performance limit. Machine load and file caching affect the time.", "",
        "## Build and update", "", "```sh",
        "nix build --no-update-lock-file",
        "nix flake check --no-update-lock-file",
        "nix run .#update-readme --no-update-lock-file", "```", "",
        "The update command runs the full comparison and a new benchmark, then writes this README and the measurement data.",
        "Nix pins the tools and test data. See [test details](docs/hackage.md) and [API use and limits](docs/api.md).", "",
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("summary", type=Path)
    parser.add_argument("--runner")
    parser.add_argument("--index")
    parser.add_argument("--system")
    parser.add_argument("--ghc-version")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    summary = json.loads(args.summary.read_text())
    data = Path("tests/hackage/benchmark.json")
    if args.check:
        benchmark = json.loads(data.read_text())
    else:
        start = time.monotonic()
        process = subprocess.Popen([args.runner, args.index], stdout=subprocess.PIPE, text=True)
        output = process.stdout.read()
        _, status, usage = os.wait4(process.pid, 0)
        process.returncode = os.waitstatus_to_exitcode(status)
        elapsed = time.monotonic() - start
        if process.returncode:
            raise RuntimeError("Benchmark failed")
        total, accepted = map(int, output.split())
        benchmark = dict(total=total, accepted=accepted, elapsed_seconds=elapsed,
                         peak_rss_bytes=int(usage.ru_maxrss * (1 if sys.platform == "darwin" else 1024)),
                         system=args.system, ghc_version=args.ghc_version)
    readme = render(summary, benchmark)
    if args.check:
        if Path("README.md").read_text() != readme:
            raise ValueError("README results differ. Run nix run .#update-readme")
    else:
        data.write_text(json.dumps(benchmark, indent=2) + "\n")
        Path("README.md").write_text(readme)


if __name__ == "__main__":
    main()
