"""Generate README results from the full comparison and a separate measurement."""
import argparse
import json
import math
from pathlib import Path
import os
import subprocess
import sys
import time


def render(summary, benchmark):
    total = summary["total"]
    ours = benchmark["parsers"]["aihc"]
    reference = benchmark["parsers"]["Cabal-syntax"]
    if benchmark["reference_version"] != summary["reference_version"]:
        raise ValueError("Benchmark reference version differs from the comparison")
    for measurement, accepted in [(ours, summary["parser_accepted"]),
                                  (reference, summary["reference_accepted"])]:
        if measurement["total"] != total or measurement["accepted"] != accepted:
            raise ValueError("Benchmark counts differ from the comparison")
        for key in ["elapsed_seconds", "peak_rss_bytes"]:
            if not math.isfinite(measurement[key]) or measurement[key] <= 0:
                raise ValueError("Benchmark measurements must be finite and positive")
    def measurement_row(label, key, divisor, unit):
        return (f"| {label} | {ours[key] / divisor:.2f} {unit} | "
                f"{reference[key] / divisor:.2f} {unit} | {ours[key] / reference[key]:.2f}× |")
    def row(label, count):
        return f"| {label} | {count:,} | {100 * count / total:.2f}% |"
    return "\n".join([
        "<!-- Generated by scripts/readme.py. Do not edit. -->",
        "# aihc-cabal-syntax", "",
        "A small Haskell library that parses `.cabal` files for the aihc compiler.",
        "It provides package data, version ranges, and condition evaluation without a runtime dependency on Cabal or Cabal-syntax.",
        "It uses Megaparsec. It does not solve dependencies or build packages.", "",
        "## Hackage results", "",
        f"The fixed Hackage index contains **{total:,} file revisions**.",
        f"The reference parser is **Cabal-syntax {summary['reference_version']}**.", "",
        "| Result | Files | All files |", "| --- | ---: | ---: |",
        row("aihc-cabal-syntax accepts", summary["parser_accepted"]),
        row("Cabal-syntax accepts", summary["reference_accepted"]),
        row("Equal converted data", summary["outcomes"]["match"]), "",
        "An accepted file does not prove full compliance.",
        "The equality test compares complete `GenericPackageDescription` values after conversion of our AST.",
        "Conversion limits can also cause differences. This library is not a complete replacement for Cabal-syntax.", "",
        "## Parse benchmark", "",
        f"Each parser reads all **{total:,} revisions** in a separate process on the same machine.", "",
        "| Measurement | aihc-cabal-syntax | Cabal-syntax | aihc / Cabal-syntax |",
        "| --- | ---: | ---: | ---: |",
        measurement_row("Elapsed time", "elapsed_seconds", 1, "s"),
        measurement_row("Peak process memory (RSS)", "peak_rss_bytes", 1048576, "MiB"), "",
        "A ratio below 1 means less time or memory than Cabal-syntax.",
        f"Measured on `{benchmark['system']}` with GHC {benchmark['ghc_version']}, `-O2`, and one RTS capability.",
        "Time includes archive input, parsing, and result evaluation through `show`.",
        "The benchmark includes rejected files. It discards each result before the next file.",
        "Each parser has one measured run. Machine load and file caching affect the time.",
        "The parsers produce different data and accept different numbers of files; these ratios include that difference.", "",
        "## Build and update", "", "```sh",
        "nix build --no-update-lock-file",
        "nix flake check --no-update-lock-file",
        "nix run .#update-readme --no-update-lock-file", "```", "",
        "The update command runs the full comparison and a new benchmark, then writes this README and the measurement data.",
        "Nix pins the tools and test data. See [test details](docs/hackage.md) and [API use and limits](docs/api.md).", "",
    ])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("summary", type=Path)
    parser.add_argument("--runner")
    parser.add_argument("--index")
    parser.add_argument("--system")
    parser.add_argument("--ghc-version")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--refresh-stats", action="store_true")
    args = parser.parse_args()
    summary = json.loads(args.summary.read_text())
    results = Path("tests/hackage/results.json")
    if args.refresh_stats and json.loads(results.read_text()) == summary:
        print("Hackage results are unchanged")
        return
    data = Path("tests/hackage/benchmark.json")
    if args.check:
        benchmark = json.loads(data.read_text())
    else:
        measurements = {}
        for name in ["Cabal-syntax", "aihc"]:
            start = time.monotonic()
            process = subprocess.Popen([args.runner, name, args.index], stdout=subprocess.PIPE, text=True)
            output = process.stdout.read()
            process.stdout.close()
            _, status, usage = os.wait4(process.pid, 0)
            process.returncode = os.waitstatus_to_exitcode(status)
            elapsed = time.monotonic() - start
            if process.returncode:
                raise RuntimeError(f"Benchmark failed: {name}")
            total, accepted = map(int, output.split())
            measurements[name] = dict(total=total, accepted=accepted, elapsed_seconds=elapsed,
                peak_rss_bytes=int(usage.ru_maxrss * (1 if sys.platform == "darwin" else 1024)))
        benchmark = dict(parsers=measurements, reference_version=summary["reference_version"],
                         system=args.system, ghc_version=args.ghc_version)
    readme = render(summary, benchmark)
    if args.check:
        if json.loads(results.read_text()) != summary:
            raise ValueError("Saved Hackage results differ from the report")
        if Path("README.md").read_text() != readme:
            raise ValueError("README results differ. Run nix run .#update-readme")
    else:
        data.write_text(json.dumps(benchmark, indent=2) + "\n")
        Path("README.md").write_text(readme)
        results.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
        if args.refresh_stats:
            Path("tests/hackage/baseline.json").write_text(results.read_text())


if __name__ == "__main__":
    main()
